---
title: "My awesome website"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

#Here are some plots

today we're making eg plots in plotly . We'll make  eg using the NYC aairbnb datasets

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Do some initial data cleaning/ subsetting. making the dataset smaller for interaction

```{r}
data("nyc_airbnb")

nyc_airbnb=
  nyc_airbnb |> 
  mutate(rating = review_scores_location /2) |> 
  select(
    rating, neighbourhood_group, neighbourhood, 
    room_type, lat, long, price) |> 
  drop_na(rating) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type=="Entire home/apt",
    price %in% 100:500
  )
```

Use plotly to make some quick plots.

First--scatter
```{r}
nyc_airbnb |> 
  mutate(text_label=str_c("Price:",price,"\nNeighbourhood:",neighbourhood)) |> 
  plot_ly(
    x= ~lat, y= ~long, color= ~price, text=~text_label,
    type="scatter", mode="markers", alpha=0.5
  )
```

Next up--box plot
```{r}
nyc_airbnb |> 
  mutate(neighbourhood=fct_reorder(neighbourhood,price)) |>  ##@@@@
  plot_ly(
    x= ~neighbourhood, y=~price, color=~neighbourhood,  ##can double click to select and compare
    type="box", colors="viridis"
  )
```

let's do a bar chart with number of rentals
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood= fct_reorder(neighbourhood,n)) |> 
  plot_ly(x=~neighbourhood, y=~n,
          type="bar")
```

